version: '3.9'

services:
  postgres:
    image: postgres:15.3-alpine
    container_name: postgres_db_udacity
    environment:
      POSTGRES_USER: romi
      POSTGRES_PASSWORD: romina
      POSTGRES_DB: reviewdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources:/docker-entrypoint-initdb.d

volumes:
  postgres_data: